package personal.anand.utils;

public interface Keys {
    String KEY_USER_ID ="KEY_USER_ID";
    String KEY_AUTH_TOKEN="KEY_AUTH_TOKEN";
    String KEY_PRODUCT_ID ="KEY_PRODUCT_ID";
    String KEY_CREATE_PRODUCT_MESSAGE ="KEY_CREATE_PRODUCT_MESSAGE";
    String KEY_CREATE_ORDER_MESSAGE="KEY_CREATE_ORDER_MESSAGE";
    String KEY_ORDER_DETAILS_MESSAGE="KEY_ORDER_DETAILS_MESSAGE";

}
